name = "WfosContainer"
components: [
  {
    prefix = "wfos.bgrxAssembly"
    componentType = assembly
    componentHandlerClassName = "wfos.bgrxassembly.BgrxassemblyHandlers"
    locationServiceUsage = RegisterAndTrackServices
    connections = [
      {
        prefix= "wfos.bgrxAssembly.rgriphcd"
        componentType= hcd
        connectionType = pekko
      },
      {
        prefix= "wfos.bgrxAssembly.lgriphcd"
        componentType= hcd
        connectionType = pekko
      },
      {
        prefix= "wfos.bgrxAssembly.lgmhcd"
        componentType=hcd
        connectionType = pekko
      },
      {
        prefix= "wfos.bgrxAssembly.pacthcd"
        componentType= hcd
        connectionType = pekko
      }
    ]
  },
  {
    prefix = "wfos.bgrxAssembly.rgriphcd"
    componentType = hcd
    componentHandlerClassName = "wfos.rgriphcd.RgriphcdHandlers"
    locationServiceUsage = RegisterOnly
  },
  {
    prefix = "wfos.bgrxAssembly.lgriphcd"
    componentType = hcd
    componentHandlerClassName = "wfos.lgriphcd.LgriphcdHandlers"
    locationServiceUsage = RegisterOnly
  },
  {
    prefix = "wfos.bgrxAssembly.lgmhcd"
    componentType = hcd
    componentHandlerClassName = "wfos.lgmhcd.LgmhcdHandlers"
    locationServiceUsage = RegisterOnly
  },
  {
    prefix = "wfos.bgrxAssembly.pacthcd"
    componentType = hcd
    componentHandlerClassName = "wfos.pacthcd.PacthcdHandlers"
    locationServiceUsage = RegisterOnly
  }
]